import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Header } from '@/components/Header'
import { Pricing } from '@/components/Pricing'
import { Features } from '@/components/Features'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<main className={inter.className}>
				<Header />
				<Pricing />
				<Features />
			</main>
		</>
	)
}
